### ISSUE TITLE
Ampersand in Header displaying as html entity code

### ISSUE THREAD

**Issue by adioni** [typemill-resources/learn#2]
While I'm able to create files / folders with an ampersand in its title, when I go and view the site, the header displays `&amp` instead of & 

[Example](https://imgur.com/a/4PgjR2E)

**Comment by trendschau** [comment]
thanks for reporting, I see the problem. Will try to fix with next release 1.4.7

**Comment by trendschau** [comment]
Fixed with upcomming release 1.4.7
