### ISSUE TITLE
notice4 type

### ISSUE THREAD

**Issue by adioni** [typemill-resources/learn#4]
Not sure if I would describe as a bug and/or feature enhancement question, but anyway:

Would it be possible to create a distinct style for a fourth notice type and have that be an available option into the visual editor?

Right now in the typemill learn theme there appears to be only three unique notice types. The original grav learn theme and other learn theme-derived forks seem to have four (e.g.: https://learn.netlify.app/en/shortcodes/notice/  [ blue, orange, green, red ] ).

**Comment by trendschau** [comment]
yes, that is no problem, i can add it to the dev-branch within the next days

**Comment by adioni** [comment]
Thank you! That addition would definitely help me out.

**Comment by trendschau** [comment]
will be deployed with next release 1.4.7 (you can use develop branch) and learn-theme version 1.1.2
