### ISSUE TITLE
Colored versions do not work

### ISSUE THREAD

**Issue by thenktor** [typemill-resources/learn#5]
Hi,

I've tried to change the color of the learn theme, but it doe not work.
Firefox tries to load a stylesheet `/themes/learn/static/css/theme-green` which does not exist on the webserver. There is a file `/themes/learn/static/css/theme-green.css` though.

See screenshots from Firefox:
![ksnip_20210719-112230](https://user-images.githubusercontent.com/371714/126136816-0a9947fe-efd2-4cb3-96a0-566a64bd7b2a.png)

and:
![ksnip_20210719-111653](https://user-images.githubusercontent.com/371714/126136113-a1594fff-9b68-4dd5-9442-5d1ce8c40af5.png)

**Comment by trendschau** [comment]
thank you, I will have a look at it asap

**Comment by trendschau** [comment]
Fixed it and will go online with version 1.1.2
